//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright Pure Storage, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortworxXcopyVolumePopulator) DeepCopyInto(out *PortworxXcopyVolumePopulator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortworxXcopyVolumePopulator.
func (in *PortworxXcopyVolumePopulator) DeepCopy() *PortworxXcopyVolumePopulator {
	if in == nil {
		return nil
	}
	out := new(PortworxXcopyVolumePopulator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortworxXcopyVolumePopulator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortworxXcopyVolumePopulatorList) DeepCopyInto(out *PortworxXcopyVolumePopulatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PortworxXcopyVolumePopulator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortworxXcopyVolumePopulatorList.
func (in *PortworxXcopyVolumePopulatorList) DeepCopy() *PortworxXcopyVolumePopulatorList {
	if in == nil {
		return nil
	}
	out := new(PortworxXcopyVolumePopulatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortworxXcopyVolumePopulatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortworxXcopyVolumePopulatorSpec) DeepCopyInto(out *PortworxXcopyVolumePopulatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortworxXcopyVolumePopulatorSpec.
func (in *PortworxXcopyVolumePopulatorSpec) DeepCopy() *PortworxXcopyVolumePopulatorSpec {
	if in == nil {
		return nil
	}
	out := new(PortworxXcopyVolumePopulatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortworxXcopyVolumePopulatorStatus) DeepCopyInto(out *PortworxXcopyVolumePopulatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortworxXcopyVolumePopulatorStatus.
func (in *PortworxXcopyVolumePopulatorStatus) DeepCopy() *PortworxXcopyVolumePopulatorStatus {
	if in == nil {
		return nil
	}
	out := new(PortworxXcopyVolumePopulatorStatus)
	in.DeepCopyInto(out)
	return out
}
